//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Farma.pe.FarmaciaService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MEDICAMENTO", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class MEDICAMENTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Farma.pe.FarmaciaService.ADVERTENCIA ADVERTENCIAField;
        
        private string CON_MEDField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.FAVORITO> FAVORITOField;
        
        private Farma.pe.FarmaciaService.FORMA_USO FORMA_USOField;
        
        private int ID_ADVField;
        
        private int ID_FORField;
        
        private int ID_LABField;
        
        private int ID_MEDField;
        
        private int ID_PREField;
        
        private int ID_SINField;
        
        private Farma.pe.FarmaciaService.LABORATORIO LABORATORIOField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO_FARMACIA> MEDICAMENTO_FARMACIAField;
        
        private string NOM_MEDField;
        
        private Farma.pe.FarmaciaService.PRESENTACION PRESENTACIONField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.PROMOCION> PROMOCIONField;
        
        private Farma.pe.FarmaciaService.SINTOMA SINTOMAField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.ADVERTENCIA ADVERTENCIA {
            get {
                return this.ADVERTENCIAField;
            }
            set {
                if ((object.ReferenceEquals(this.ADVERTENCIAField, value) != true)) {
                    this.ADVERTENCIAField = value;
                    this.RaisePropertyChanged("ADVERTENCIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CON_MED {
            get {
                return this.CON_MEDField;
            }
            set {
                if ((object.ReferenceEquals(this.CON_MEDField, value) != true)) {
                    this.CON_MEDField = value;
                    this.RaisePropertyChanged("CON_MED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.FAVORITO> FAVORITO {
            get {
                return this.FAVORITOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAVORITOField, value) != true)) {
                    this.FAVORITOField = value;
                    this.RaisePropertyChanged("FAVORITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.FORMA_USO FORMA_USO {
            get {
                return this.FORMA_USOField;
            }
            set {
                if ((object.ReferenceEquals(this.FORMA_USOField, value) != true)) {
                    this.FORMA_USOField = value;
                    this.RaisePropertyChanged("FORMA_USO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ADV {
            get {
                return this.ID_ADVField;
            }
            set {
                if ((this.ID_ADVField.Equals(value) != true)) {
                    this.ID_ADVField = value;
                    this.RaisePropertyChanged("ID_ADV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_FOR {
            get {
                return this.ID_FORField;
            }
            set {
                if ((this.ID_FORField.Equals(value) != true)) {
                    this.ID_FORField = value;
                    this.RaisePropertyChanged("ID_FOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LAB {
            get {
                return this.ID_LABField;
            }
            set {
                if ((this.ID_LABField.Equals(value) != true)) {
                    this.ID_LABField = value;
                    this.RaisePropertyChanged("ID_LAB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MED {
            get {
                return this.ID_MEDField;
            }
            set {
                if ((this.ID_MEDField.Equals(value) != true)) {
                    this.ID_MEDField = value;
                    this.RaisePropertyChanged("ID_MED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PRE {
            get {
                return this.ID_PREField;
            }
            set {
                if ((this.ID_PREField.Equals(value) != true)) {
                    this.ID_PREField = value;
                    this.RaisePropertyChanged("ID_PRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SIN {
            get {
                return this.ID_SINField;
            }
            set {
                if ((this.ID_SINField.Equals(value) != true)) {
                    this.ID_SINField = value;
                    this.RaisePropertyChanged("ID_SIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.LABORATORIO LABORATORIO {
            get {
                return this.LABORATORIOField;
            }
            set {
                if ((object.ReferenceEquals(this.LABORATORIOField, value) != true)) {
                    this.LABORATORIOField = value;
                    this.RaisePropertyChanged("LABORATORIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO_FARMACIA> MEDICAMENTO_FARMACIA {
            get {
                return this.MEDICAMENTO_FARMACIAField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTO_FARMACIAField, value) != true)) {
                    this.MEDICAMENTO_FARMACIAField = value;
                    this.RaisePropertyChanged("MEDICAMENTO_FARMACIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_MED {
            get {
                return this.NOM_MEDField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_MEDField, value) != true)) {
                    this.NOM_MEDField = value;
                    this.RaisePropertyChanged("NOM_MED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.PRESENTACION PRESENTACION {
            get {
                return this.PRESENTACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PRESENTACIONField, value) != true)) {
                    this.PRESENTACIONField = value;
                    this.RaisePropertyChanged("PRESENTACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.PROMOCION> PROMOCION {
            get {
                return this.PROMOCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.PROMOCIONField, value) != true)) {
                    this.PROMOCIONField = value;
                    this.RaisePropertyChanged("PROMOCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.SINTOMA SINTOMA {
            get {
                return this.SINTOMAField;
            }
            set {
                if ((object.ReferenceEquals(this.SINTOMAField, value) != true)) {
                    this.SINTOMAField = value;
                    this.RaisePropertyChanged("SINTOMA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADVERTENCIA", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class ADVERTENCIA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DES_ADVField;
        
        private int ID_ADVField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_ADV {
            get {
                return this.DES_ADVField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_ADVField, value) != true)) {
                    this.DES_ADVField = value;
                    this.RaisePropertyChanged("DES_ADV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ADV {
            get {
                return this.ID_ADVField;
            }
            set {
                if ((this.ID_ADVField.Equals(value) != true)) {
                    this.ID_ADVField = value;
                    this.RaisePropertyChanged("ID_ADV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FORMA_USO", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class FORMA_USO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DES_FORField;
        
        private int ID_FORField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_FOR {
            get {
                return this.DES_FORField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_FORField, value) != true)) {
                    this.DES_FORField = value;
                    this.RaisePropertyChanged("DES_FOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_FOR {
            get {
                return this.ID_FORField;
            }
            set {
                if ((this.ID_FORField.Equals(value) != true)) {
                    this.ID_FORField = value;
                    this.RaisePropertyChanged("ID_FOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LABORATORIO", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class LABORATORIO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ID_LABField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTOField;
        
        private string NOM_LABField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LAB {
            get {
                return this.ID_LABField;
            }
            set {
                if ((this.ID_LABField.Equals(value) != true)) {
                    this.ID_LABField = value;
                    this.RaisePropertyChanged("ID_LAB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_LAB {
            get {
                return this.NOM_LABField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_LABField, value) != true)) {
                    this.NOM_LABField = value;
                    this.RaisePropertyChanged("NOM_LAB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PRESENTACION", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class PRESENTACION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DES_PREField;
        
        private int ID_PREField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_PRE {
            get {
                return this.DES_PREField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_PREField, value) != true)) {
                    this.DES_PREField = value;
                    this.RaisePropertyChanged("DES_PRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PRE {
            get {
                return this.ID_PREField;
            }
            set {
                if ((this.ID_PREField.Equals(value) != true)) {
                    this.ID_PREField = value;
                    this.RaisePropertyChanged("ID_PRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SINTOMA", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class SINTOMA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DES_SINField;
        
        private int ID_SINField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_SIN {
            get {
                return this.DES_SINField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_SINField, value) != true)) {
                    this.DES_SINField = value;
                    this.RaisePropertyChanged("DES_SIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_SIN {
            get {
                return this.ID_SINField;
            }
            set {
                if ((this.ID_SINField.Equals(value) != true)) {
                    this.ID_SINField = value;
                    this.RaisePropertyChanged("ID_SIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FAVORITO", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class FAVORITO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ID_FAVField;
        
        private int ID_MEDField;
        
        private int ID_USUField;
        
        private Farma.pe.FarmaciaService.MEDICAMENTO MEDICAMENTOField;
        
        private Farma.pe.FarmaciaService.USUARIO USUARIOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_FAV {
            get {
                return this.ID_FAVField;
            }
            set {
                if ((this.ID_FAVField.Equals(value) != true)) {
                    this.ID_FAVField = value;
                    this.RaisePropertyChanged("ID_FAV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MED {
            get {
                return this.ID_MEDField;
            }
            set {
                if ((this.ID_MEDField.Equals(value) != true)) {
                    this.ID_MEDField = value;
                    this.RaisePropertyChanged("ID_MED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_USU {
            get {
                return this.ID_USUField;
            }
            set {
                if ((this.ID_USUField.Equals(value) != true)) {
                    this.ID_USUField = value;
                    this.RaisePropertyChanged("ID_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.MEDICAMENTO MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.USUARIO USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MEDICAMENTO_FARMACIA", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class MEDICAMENTO_FARMACIA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int ID_FARField;
        
        private int ID_MEDField;
        
        private Farma.pe.FarmaciaService.MEDICAMENTO MEDICAMENTOField;
        
        private decimal PRECIOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_FAR {
            get {
                return this.ID_FARField;
            }
            set {
                if ((this.ID_FARField.Equals(value) != true)) {
                    this.ID_FARField = value;
                    this.RaisePropertyChanged("ID_FAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MED {
            get {
                return this.ID_MEDField;
            }
            set {
                if ((this.ID_MEDField.Equals(value) != true)) {
                    this.ID_MEDField = value;
                    this.RaisePropertyChanged("ID_MED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.MEDICAMENTO MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PRECIO {
            get {
                return this.PRECIOField;
            }
            set {
                if ((this.PRECIOField.Equals(value) != true)) {
                    this.PRECIOField = value;
                    this.RaisePropertyChanged("PRECIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PROMOCION", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class PROMOCION : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DES_PROField;
        
        private int ID_FARField;
        
        private int ID_MEDField;
        
        private int ID_PROField;
        
        private Farma.pe.FarmaciaService.MEDICAMENTO MEDICAMENTOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DES_PRO {
            get {
                return this.DES_PROField;
            }
            set {
                if ((object.ReferenceEquals(this.DES_PROField, value) != true)) {
                    this.DES_PROField = value;
                    this.RaisePropertyChanged("DES_PRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_FAR {
            get {
                return this.ID_FARField;
            }
            set {
                if ((this.ID_FARField.Equals(value) != true)) {
                    this.ID_FARField = value;
                    this.RaisePropertyChanged("ID_FAR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MED {
            get {
                return this.ID_MEDField;
            }
            set {
                if ((this.ID_MEDField.Equals(value) != true)) {
                    this.ID_MEDField = value;
                    this.RaisePropertyChanged("ID_MED");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PRO {
            get {
                return this.ID_PROField;
            }
            set {
                if ((this.ID_PROField.Equals(value) != true)) {
                    this.ID_PROField = value;
                    this.RaisePropertyChanged("ID_PRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.MEDICAMENTO MEDICAMENTO {
            get {
                return this.MEDICAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MEDICAMENTOField, value) != true)) {
                    this.MEDICAMENTOField = value;
                    this.RaisePropertyChanged("MEDICAMENTO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class USUARIO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CORREO_USUField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.FAVORITO> FAVORITOField;
        
        private int ID_USUField;
        
        private string NOM_USUField;
        
        private string PASS_USUField;
        
        private System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.PERSONA> PERSONAField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CORREO_USU {
            get {
                return this.CORREO_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.CORREO_USUField, value) != true)) {
                    this.CORREO_USUField = value;
                    this.RaisePropertyChanged("CORREO_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.FAVORITO> FAVORITO {
            get {
                return this.FAVORITOField;
            }
            set {
                if ((object.ReferenceEquals(this.FAVORITOField, value) != true)) {
                    this.FAVORITOField = value;
                    this.RaisePropertyChanged("FAVORITO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_USU {
            get {
                return this.ID_USUField;
            }
            set {
                if ((this.ID_USUField.Equals(value) != true)) {
                    this.ID_USUField = value;
                    this.RaisePropertyChanged("ID_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_USU {
            get {
                return this.NOM_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_USUField, value) != true)) {
                    this.NOM_USUField = value;
                    this.RaisePropertyChanged("NOM_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASS_USU {
            get {
                return this.PASS_USUField;
            }
            set {
                if ((object.ReferenceEquals(this.PASS_USUField, value) != true)) {
                    this.PASS_USUField = value;
                    this.RaisePropertyChanged("PASS_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.PERSONA> PERSONA {
            get {
                return this.PERSONAField;
            }
            set {
                if ((object.ReferenceEquals(this.PERSONAField, value) != true)) {
                    this.PERSONAField = value;
                    this.RaisePropertyChanged("PERSONA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PERSONA", Namespace="http://schemas.datacontract.org/2004/07/ServicioFarma")]
    public partial class PERSONA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string APEM_PERField;
        
        private string APEP_PERField;
        
        private System.Nullable<System.DateTime> FNAC_PERField;
        
        private int ID_USUField;
        
        private string NOM_PERField;
        
        private int PER_IDField;
        
        private Farma.pe.FarmaciaService.USUARIO USUARIOField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APEM_PER {
            get {
                return this.APEM_PERField;
            }
            set {
                if ((object.ReferenceEquals(this.APEM_PERField, value) != true)) {
                    this.APEM_PERField = value;
                    this.RaisePropertyChanged("APEM_PER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APEP_PER {
            get {
                return this.APEP_PERField;
            }
            set {
                if ((object.ReferenceEquals(this.APEP_PERField, value) != true)) {
                    this.APEP_PERField = value;
                    this.RaisePropertyChanged("APEP_PER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FNAC_PER {
            get {
                return this.FNAC_PERField;
            }
            set {
                if ((this.FNAC_PERField.Equals(value) != true)) {
                    this.FNAC_PERField = value;
                    this.RaisePropertyChanged("FNAC_PER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_USU {
            get {
                return this.ID_USUField;
            }
            set {
                if ((this.ID_USUField.Equals(value) != true)) {
                    this.ID_USUField = value;
                    this.RaisePropertyChanged("ID_USU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOM_PER {
            get {
                return this.NOM_PERField;
            }
            set {
                if ((object.ReferenceEquals(this.NOM_PERField, value) != true)) {
                    this.NOM_PERField = value;
                    this.RaisePropertyChanged("NOM_PER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PER_ID {
            get {
                return this.PER_IDField;
            }
            set {
                if ((this.PER_IDField.Equals(value) != true)) {
                    this.PER_IDField = value;
                    this.RaisePropertyChanged("PER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Farma.pe.FarmaciaService.USUARIO USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FarmaciaService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/listarMedicamentos", ReplyAction="http://tempuri.org/IService1/listarMedicamentosResponse")]
        System.IAsyncResult BeginlistarMedicamentos(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> EndlistarMedicamentos(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Farma.pe.FarmaciaService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class listarMedicamentosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public listarMedicamentosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Farma.pe.FarmaciaService.IService1>, Farma.pe.FarmaciaService.IService1 {
        
        private BeginOperationDelegate onBeginlistarMedicamentosDelegate;
        
        private EndOperationDelegate onEndlistarMedicamentosDelegate;
        
        private System.Threading.SendOrPostCallback onlistarMedicamentosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<listarMedicamentosCompletedEventArgs> listarMedicamentosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Farma.pe.FarmaciaService.IService1.BeginlistarMedicamentos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlistarMedicamentos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> Farma.pe.FarmaciaService.IService1.EndlistarMedicamentos(System.IAsyncResult result) {
            return base.Channel.EndlistarMedicamentos(result);
        }
        
        private System.IAsyncResult OnBeginlistarMedicamentos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Farma.pe.FarmaciaService.IService1)(this)).BeginlistarMedicamentos(callback, asyncState);
        }
        
        private object[] OnEndlistarMedicamentos(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> retVal = ((Farma.pe.FarmaciaService.IService1)(this)).EndlistarMedicamentos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlistarMedicamentosCompleted(object state) {
            if ((this.listarMedicamentosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.listarMedicamentosCompleted(this, new listarMedicamentosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void listarMedicamentosAsync() {
            this.listarMedicamentosAsync(null);
        }
        
        public void listarMedicamentosAsync(object userState) {
            if ((this.onBeginlistarMedicamentosDelegate == null)) {
                this.onBeginlistarMedicamentosDelegate = new BeginOperationDelegate(this.OnBeginlistarMedicamentos);
            }
            if ((this.onEndlistarMedicamentosDelegate == null)) {
                this.onEndlistarMedicamentosDelegate = new EndOperationDelegate(this.OnEndlistarMedicamentos);
            }
            if ((this.onlistarMedicamentosCompletedDelegate == null)) {
                this.onlistarMedicamentosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlistarMedicamentosCompleted);
            }
            base.InvokeAsync(this.onBeginlistarMedicamentosDelegate, null, this.onEndlistarMedicamentosDelegate, this.onlistarMedicamentosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Farma.pe.FarmaciaService.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Farma.pe.FarmaciaService.IService1>, Farma.pe.FarmaciaService.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Farma.pe.FarmaciaService.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginlistarMedicamentos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("listarMedicamentos", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> EndlistarMedicamentos(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO> _result = ((System.Collections.ObjectModel.ObservableCollection<Farma.pe.FarmaciaService.MEDICAMENTO>)(base.EndInvoke("listarMedicamentos", _args, result)));
                return _result;
            }
        }
    }
}
